# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import skeleton_pb2 as skeleton__pb2


class SkeletonStub(object):
  """Defining a service "Greeter" using proto file
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.MsgTransfer = channel.unary_unary(
        '/Skeleton/MsgTransfer',
        request_serializer=skeleton__pb2.MsgRequest.SerializeToString,
        response_deserializer=skeleton__pb2.MsgResponse.FromString,
        )


class SkeletonServicer(object):
  """Defining a service "Greeter" using proto file
  """

  def MsgTransfer(self, request, context):
    """Unary RPC that receives HelloRequest and returns HelloReply
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SkeletonServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'MsgTransfer': grpc.unary_unary_rpc_method_handler(
          servicer.MsgTransfer,
          request_deserializer=skeleton__pb2.MsgRequest.FromString,
          response_serializer=skeleton__pb2.MsgResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Skeleton', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
