# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import skeleton_pb2 as skeleton__pb2


class SkeletonStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendMsg = channel.unary_unary(
        '/Skeleton/SendMsg',
        request_serializer=skeleton__pb2.Events.SerializeToString,
        response_deserializer=skeleton__pb2.Events.FromString,
        )


class SkeletonServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendMsg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SkeletonServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendMsg': grpc.unary_unary_rpc_method_handler(
          servicer.SendMsg,
          request_deserializer=skeleton__pb2.Events.FromString,
          response_serializer=skeleton__pb2.Events.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Skeleton', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
