# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import example_pb2 as example__pb2


class RPCStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.MsgDelivery = channel.unary_unary(
        '/RPC/MsgDelivery',
        request_serializer=example__pb2.Event.SerializeToString,
        response_deserializer=example__pb2.Event.FromString,
        )


class RPCServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def MsgDelivery(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RPCServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'MsgDelivery': grpc.unary_unary_rpc_method_handler(
          servicer.MsgDelivery,
          request_deserializer=example__pb2.Event.FromString,
          response_serializer=example__pb2.Event.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RPC', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
